import {
  Calendar,
  Check,
  Code,
  EllipsisVertical,
  EyeIcon,
  HeartIcon,
  Info,
  Loader2,
  Plus,
  Settings,
  Trash,
  X,
  Edit,
  AlignEndHorizontal,
  CircleDollarSign,
  ImageIcon,
} from "lucide-react";

export const Icons = {
  code: Code,
  settings: Settings,
  add: Plus,
  ellipsis: EllipsisVertical,
  spinner: Loader2,
  trash: Trash,
  calender: Calendar,
  eye: EyeIcon,
  likes: HeartIcon,
  info: Info,
  tick: Check,
  cross: X,
  edit: Edit,
  result: AlignEndHorizontal,
  registration: CircleDollarSign,
  image: ImageIcon,
};
